[package]
name = "smart_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.26"
spl-token = "3.5.0"
thiserror = "1.0"
borsh = "0.10.3"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = false
